### ISSUE TITLE
Fine tuning SSD

### ISSUE THREAD

**Issue by semin-park** [ChintanTrivedi/DeepGamingAI_FPS#1]
Hi, first of all, thank you for sharing this project. I think it's really cool :)

I just have a small question about training the SSD for new labels. From the look of your `data` folder, it seems like you've used ~80 images to fine tune the ssd model to detect the objects you've used for this project, am I right?

I'm curious if that was enough to make it detect as well as shown in the demo GIF. I have never trained an SSD before so I guess I'm just curious if fine tuning is that sample efficient. I was expecting the amount of data needed to fine tune to be at least an order of magnitude greater :P.

Thanks again for this btw! Very interesting project!

**Comment by ChintanTrivedi** [comment]
I'm using a pre-trained model to start with, which was already trained to detect these classes and many other classes as well. I only retrained in order to detect a total of just the 3 classes I was interested in.

**Comment by semin-park** [comment]
Aha alright thanks!
